config/routes.rb
Rails.application.routes.draw do
  resources :interest_calculations

  root 'interest_calculations#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest_calculation.rb
class InterestCalculation < ApplicationRecord

  validates_presence_of :principal_amount, numericality: true
  validates_presence_of :interest_rate, numericality: true
  validates_presence_of :duration
  validates_presence_of :frequency

  validates :principal_amount, numericality: true
  validates :interest_rate, numericality: true
  
  def self.compound_interest(p, r, t, n)
    a = p * (1 + r/n) ** (n*t)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/interest_calculations_controller.rb
class InterestCalculationsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_interest_calculation, only: [:show, :edit, :update, :destroy]

  def index
    @interest_calculations = InterestCalculation.order(sort_column + ' ' + sort_direction)
  end

  def show
  end

  def new
    @interest_calculation = InterestCalculation.new
  end

  def edit
  end

  def create
    calculate_amount(params)
    @interest_calculation = InterestCalculation.new(interest_calculation_params)
    respond_to do |format|
      if @interest_calculation.save
        format.html { redirect_to @interest_calculation, notice: 'Interest calculation was successfully created.' }
        format.json { render :show, status: :created, location: @interest_calculation }
      else
        format.html { render :new }
        format.json { render json: @interest_calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @interest_calculation.update(interest_calculation_params)
        calculate_amount(params)
        @interest_calculation.update(interest_calculation_params)
        format.html { redirect_to @interest_calculation, notice: 'Interest calculation was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest_calculation }
      else
        format.html { render :edit }
        format.json { render json: @interest_calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @interest_calculation.destroy
    respond_to do |format|
      format.html { redirect_to interest_calculations_url, notice: 'Interest calculation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_interest_calculation
      @interest_calculation = InterestCalculation.find(params[:id])
    end

    def interest_calculation_params
      params.require(:interest_calculation).permit(:principal_amount, :interest_rate, :duration, :frequency, :final_amount)
    end

    def calculate_amount(params)
      principal_amount  = params[:interest_calculation][:principal_amount].to_d
      interest_rate     = params[:interest_calculation][:interest_rate].to_d/100
      time              = params[:interest_calculation][:duration].to_i
      frequency         = params[:interest_calculation][:frequency].to_i
  
      result = InterestCalculation.compound_interest(principal_amount, interest_rate, time, frequency)
      amount = { 'final_amount' => result.to_d.truncate(10) }
      params[:interest_calculation].merge!(amount)
    end

    def sort_column
      InterestCalculation.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/views/interest_calculations/_form.html.erb
<%= form_with(model: interest_calculation, local: true) do |form| %>
  <p>
    <%= form.label 'Principal amount (£)' %><br>
    <%= form.text_field :principal_amount %>
  </p>
  <p>
    <%= form.label 'Interest rate (%)' %><br>
    <%= form.text_field :interest_rate %>
  </p>
  <p>
    <%= form.label 'Duration (years)' %><br>
    <%= form.select :duration, (1..25) %>
  </p>
  <p>
    <%= form.label 'Times compounded per year' %><br>
    <%= form.select :frequency, :'- select -' => nil, :'1' => 1, :'12' => 12, :'365' => 365 %>
  </p>

  <% if @interest_calculation %>

    <p>
      <%= form.label 'Total value at end of term (£)' %><br>
      <%= form.text_field :final_amount, :value => number_with_precision(@interest_calculation.final_amount, :precision => 2) %>
    </p>
    
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>

  <% if interest_calculation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interest_calculation.errors.count, "error") %> prohibited this calculation from being completed:</h2>

      <ul>
        <% interest_calculation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/interest_calculations/_results.html.erb
<%= form_with(model: interest_calculation, local: true) do |form| %>
    <p>
      <%= form.label 'Principal amount (£)' %><br>
      <%= form.text_field :principal_amount, :value => @interest_calculation.principal_amount, :readonly => true %>
    </p>
    <p>
      <%= form.label 'Interest rate (%)' %><br>
      <%= form.text_field :interest_rate, :value => @interest_calculation.interest_rate, :readonly => true %>
    </p>
    <p>
      <%= form.label 'Duration (years)' %><br>
      <%= form.text_field :duration, :value => @interest_calculation.duration, :readonly => true %>
    </p>
    <p>
      <%= form.label 'Times compounded per year' %><br>
      <%= form.text_field :frequency, :value => @interest_calculation.frequency, :readonly => true %>
    </p>
    <p>
      <%= form.label 'Total value at end of term (£)' %><br>
      <%= form.text_field :final_amount, :value => number_with_precision(@interest_calculation.final_amount, :precision => 2) %>
    </p>
<% end %>

app/views/interest_calculations/edit.html.erb
<h1>Editing Interest Calculation</h1>

<%= render 'form', interest_calculation: @interest_calculation %>

<%= link_to 'Show', @interest_calculation %> |
<%= link_to 'Back', interest_calculations_path %>

app/views/interest_calculations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interest Calculations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    <tr>
      <th><%= sortable 'id', 'ID' %></th>
      <th><%= sortable 'principal_amount', 'Principal amount (£)' %></th>
      <th><%= sortable 'interest_rate', 'Interest rate (%)' %></th>
      <th><%= sortable 'duration', 'Duration (years)' %></th>
      <th><%= sortable 'frequency', 'Frequency per year' %></th>
      <th><%= sortable 'final_amount', 'Final Amount (£)' %></th>
    </tr>
  </thead>

  <tbody>

    <% @interest_calculations.each do |interest_calculation| %>
      <tr>
        <td><%= interest_calculation.id %></td>
        <td><%= interest_calculation.principal_amount %></td>
        <td><%= interest_calculation.interest_rate %></td>
        <td><%= interest_calculation.duration %></td>
        <td><%= interest_calculation.frequency %></td>
        <td><%= number_with_precision(interest_calculation.final_amount, :precision => 2) %></td>
        <td><%= link_to 'Edit', edit_interest_calculation_path(interest_calculation) %></td>
        <td><%= link_to 'Delete', interest_calculation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest Calculation', new_interest_calculation_path %>

app/views/interest_calculations/new.html.erb
<h1>New Interest Calculation</h1>

<%= render 'form', interest_calculation: @interest_calculation %>

<%= link_to 'Back', interest_calculations_path %>

app/views/interest_calculations/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'results', interest_calculation: @interest_calculation %>

<%= link_to 'Edit', edit_interest_calculation_path(@interest_calculation) %> |
<%= link_to 'Back', interest_calculations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompoundInterestCalculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>